# Turn off TV at midnight
- id: '1599685242871'
  alias: Turn off TV at midnight
  description: ''
  trigger:
  - at: 03:35:00
    platform: time
  condition:
  - condition: device
    device_id: 2b8dfdff898542f98471c05728c644bf
    domain: media_player
    entity_id: media_player.living_room_tv
    type: is_on
  action:
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_off
  mode: single
# Auto TV On
- id: '1618420788115'
  alias: Auto TV On maghrib
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    entity_id: media_player.living_room_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.select_source
    data:
      source: HDMI
    entity_id: media_player.living_room_tv
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    entity_id: media_player.living_room_tv
  mode: single
# cleanup motion folders
- id: '1618420788116'
  alias: Cleanup motion at midnight
  description: ''
  mode: single
  trigger:
    - platform: time
      at: '00:00:00'
  condition: []
  action:
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_6
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_5
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_2
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_4
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_7
    - service: shell_command.cam_cleanup
      data:
        folder: ipcam_3
# on motion camera 6 
- id: '1622010139182'
  alias: on motion - 2nd floor entrance
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_6
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_6/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename024
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_6
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_6/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '6'
        channel: Indoor cameras
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: Someone is at the 2nd floor entrance
  mode: single
# on motion camera 2
- id: '1622018300153'
  alias: on motion - 1st floor entrance
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_2
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_2/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename020
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_2
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_2/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '2'
        channel: Indoor cameras
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: Someone is at the 1st floor entrance
  mode: single
# on motion camera 4
- id: '1622018482810'
  alias: on motion - garage
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_4
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_4/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename022
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_4
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_4/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '4'
        channel: Outdoor cameras
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: Someone is outside the garage
  mode: single
# on motion camera 5
- id: '1622018652337'
  alias: on motion - backyard
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_5
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_5/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename023
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_5
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_5/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '5'
        channel: Outdoor cameras
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: Someone is in the backyard
  mode: single
# on motion camera 7
- id: '1622018986698'
  alias: on motion - front yard
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_7
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_7/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename025
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_7
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_7/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '7'
        channel: Outdoor cameras
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: Someone is at the front yard
  mode: single
# on motion camera 3
- id: '1622019496381'
  alias: on motion - anooma
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.ipcam_motion_3
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /media/ipcam_3/snapshot_latest.jpg
    entity_id: camera.ipcam_profilename021
  - service: shell_command.cam_copy_latest
    data:
      folder: /media/ipcam_3
  - service: notify.all_devices
    data_template:
      data:
        image: /media/local/ipcam_3/snapshot_latest.jpg
        timeout: 600
        clickAction: /lovelace/motion
        url: /lovelace/motion
        tag: '3'
        channel: anooma alert
        actions:
        - action: URI
          title: Watch stream
          uri: app://com.hikvision.hikconnect
      title: Motion detected
      message: anooma alert
  mode: single
