# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  time_zone: Asia/Amman
  unit_system: metric
  name: Home
  latitude: !secret ha_lat
  longitude: !secret ha_long

frontend:
  themes: !include_dir_merge_named themes

sun:

device_tracker:
  - platform: luci
    host: !secret luci_host
    username: !secret luci_username
    password: !secret luci_password
    ssl: true
    verify_ssl : false

recorder:
  purge_keep_days: 2
  commit_interval: 15
  exclude:
    domains:
      - automation
      - updater
      - media_player
    event_types:
      - call_service

shell_command:
  pi_restart_cameras: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.0.74 "sudo systemctl restart camplayer"'
  pi_shutdown_cameras: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.0.74 "sudo systemctl stop camplayer"'
  pi_restart_system: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.0.74 "sudo reboot"'
  pi_shutdown_system: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.0.74 "sudo shutdown -P now"'
  cam_copy_latest: "cp -f \"{{folder}}/snapshot_latest.jpg\" \"{{folder}}/snapshot_{{now()}}.jpg\""
  cam_cleanup: "rm -rf \"/media/{{folder}}\""

ffmpeg:
stream:

camera:
  - platform: local_file
    name: motion_2nd_floor_entrance
    file_path: /media/ipcam_6/snapshot_latest.jpg
  - platform: local_file
    name: motion_1st_floor_entrance
    file_path: /media/ipcam_2/snapshot_latest.jpg
  - platform: local_file
    name: motion_backyard
    file_path: /media/ipcam_5/snapshot_latest.jpg
  - platform: local_file
    name: motion_garage
    file_path: /media/ipcam_4/snapshot_latest.jpg
  - platform: local_file
    name: motion_outdoor_entryway
    file_path: /media/ipcam_7/snapshot_latest.jpg
  - platform: local_file
    name: motion_anooma
    file_path: /media/ipcam_3/snapshot_latest.jpg


binary_sensor:
  - platform: hikvision
    host: 192.168.0.220
    username: !secret hik_user
    password: !secret hik_pass

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_nokia_7_plus
      - service: mobile_app_nokia_6_1
      - service: mobile_app_sm_n950f
      - service: mobile_app_sm_a530f
      - service: mobile_app_nokia_6_1_plus
      - service: mobile_app_sm_m625f

automation: !include automations.yaml

switch:
  - platform: qbittorrent_alternative_speed
    host: torrent.home.io
    username: !secret localserver_user
    password: !secret localserver_pass
    port: !secret qbt_port
    name: qbittorrent alt speed

sensor:
  - platform: uptime
    name: Time Online

  - platform: qbittorrent
    url: !secret qbt_url
    username: !secret localserver_user
    password: !secret localserver_pass

  - platform: radarr
    host: !secret radarr_host
    port: !secret radarr_port
    api_key: !secret radarr_api_key 
    monitored_conditions:
      - upcoming
      - commands
      - status

# vacuum:  
#   - platform: eufy_vacuum
# eufy_vacuum:
#   devices:
#     name: RoboVac
#     address: 192.168.0.161
#     access_token: !secret eufy_token
#     id: !secret eufy_id
#     type: T2118
