# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:


homeassistant:
  customize: !include customize.yaml
  time_zone: Asia/Amman
  unit_system: metric
  name: Home
  latitude: !secret ha_lat
  longitude: !secret ha_long

http:
 server_port : 80

frontend:
  themes: !include_dir_merge_named themes

sun:

device_tracker:
  - platform: luci
    host: !secret luci_host
    username: !secret luci_username
    password: !secret luci_password
    ssl: true
    verify_ssl : false

recorder:
  purge_keep_days: 2
  commit_interval: 15
  exclude:
    domains:
      - automation
      - updater
      - media_player
    event_types:
      - call_service

# https://blog.ceard.tech/2020/05/home-assistant-docker-and-using-ssh.html 
shell_command:
  pi_restart_cameras: 'ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new pi@192.168.0.74 "sudo systemctl restart camplayer"'
  pi_shutdown_cameras: 'ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new pi@192.168.0.74 "sudo systemctl stop camplayer"'
  pi_restart_system: 'ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new pi@192.168.0.74 "sudo reboot"'
  pi_shutdown_system: 'ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new pi@192.168.0.74 "sudo shutdown -P now"'
  cam_copy_latest: "cp -f \"{{folder}}/snapshot_latest.jpg\" \"{{folder}}/snapshot_{{now()}}.jpg\""
  cam_cleanup: "find /media/{{folder}} -type f -name \"*.jpg\" -exec rm {} \\;"
  cam_rm_excess: "/config/rm_excess.sh '{{folder}}'"

ffmpeg:
stream:

camera:
  - platform: local_file
    name: motion_2nd_floor_entrance
    file_path: /media/ipcam_6/snapshot_latest.jpg
  - platform: local_file
    name: motion_1st_floor_entrance
    file_path: /media/ipcam_2/snapshot_latest.jpg
  - platform: local_file
    name: motion_backyard
    file_path: /media/ipcam_5/snapshot_latest.jpg
  - platform: local_file
    name: motion_garage
    file_path: /media/ipcam_4/snapshot_latest.jpg
  - platform: local_file
    name: motion_outdoor_entryway
    file_path: /media/ipcam_7/snapshot_latest.jpg
  - platform: local_file
    name: motion_anooma
    file_path: /media/ipcam_3/snapshot_latest.jpg


binary_sensor:
  - platform: hikvision
    host: 192.168.0.220
    username: !secret hik_user
    password: !secret hik_pass

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_nokia_7_plus
      - service: mobile_app_nokia_6_1
      - service: mobile_app_sm_n950f
      - service: mobile_app_sm_a530f
      - service: mobile_app_nokia_6_1_plus
      - service: mobile_app_sm_m625f

automation: !include automations.yaml

switch:
  #- platform: qbittorrent_alternative_speed
  #  host: torrent.home.io
  #  username: !secret localserver_user
  ##  password: !secret localserver_pass
  ##  port: !secret qbt_port
  ##  name: qbittorrent alt speed

sensor:
  - platform: uptime
    name: Time Online
  # hp printer sensors
  - platform: snmp
    name: HP Printer Toner Color
    host: 192.168.0.230
    baseoid: 1.3.6.1.2.1.43.12.1.1.4.1.1
    username: !secret snmp_user
    auth_key: !secret snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret snmp_key
    priv_protocol: des
    version: '3'
  - platform: snmp
    name: HP Printer Uptime
    host: 192.168.0.230
    baseoid: 1.3.6.1.2.1.1.3.0
    accept_errors: true
    unit_of_measurement: "minutes"
    value_template: "{{((value | int) / 6000) | int}}"
    username: !secret snmp_user
    auth_key: !secret snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret snmp_key
    priv_protocol: des
    version: '3'
  - platform: snmp
    name: HP Printer Toner Level
    host: 192.168.0.230
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.1
    unit_of_measurement: "%"
    username: !secret snmp_user
    auth_key: !secret snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret snmp_key
    priv_protocol: des
    version: '3'
  - platform: snmp
    name: HP Printer Total Pages Printed
    host: 192.168.0.230
    baseoid: 1.3.6.1.2.1.43.10.2.1.4.1.1
    unit_of_measurement: "pages"
    username: !secret snmp_user
    auth_key: !secret snmp_key
    auth_protocol: hmac-sha
    priv_key: !secret snmp_key
    priv_protocol: des
    version: '3'
    

 ## - platform: qbittorrent
  ##  url: !secret qbt_url
  ##  username: !secret localserver_user
   ## password: !secret localserver_pass

  - platform: radarr
    host: !secret radarr_host
    port: !secret radarr_port
    api_key: !secret radarr_api_key 
    monitored_conditions:
      - upcoming
      - commands
      - status

# vacuum:  
#   - platform: eufy_vacuum
# eufy_vacuum:
#   devices:
#     name: RoboVac
#     address: 192.168.0.161
#     access_token: !secret eufy_token
#     id: !secret eufy_id
#     type: T2118
